Homework 2
infinum-academy/js-react-academy-2024-Trexlo pull request #3
Opened 2024-07-05 19:37 UTC by Trexlo

2024-07-07 16:46 UTC, ante-pesorda requested changes
Evo prve runde reviewa.
Dobro je odrađeno, ali može još malo bolje 💪

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/src/components/features/shows/ReviewForm/ReviewForm.tsx
> +            return;
Ovdje bi stavio neki alert jer kad se ne odabere rating, nema nikakvog upozorenja

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/public/next.svg
očistiti

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/public/vercel.svg
počistiti

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/src/app/page.tsx
> +import { createRef, useCallback, useRef, useState } from "react";
počistiti hookove koji se ne koriste

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/src/app/page.tsx
> +
```suggestion
```

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/src/components/features/shows/ReviewForm/ReviewForm.tsx
> +    const ratingInput = document.getElementById('rating-input') as HTMLInputElement;
getElementById nije najbolja praksa koristit u Reactu. Alternativa bi bio useRef hook, ali mislim da nam ni za njim nema potrebe.
```suggestion
```

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/src/components/features/shows/ReviewForm/ReviewForm.tsx
> +    const [starRatingValue, setStarRatingValue] = useState(0);
```suggestion
    const [rating, setRating] = useState(0);
    const [comment, setComment] = useState("");
```

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/src/components/features/shows/ReviewForm/ReviewForm.tsx
> +        setStarRatingValue(0);
```suggestion
        setComment("");
        setRating(0);
```

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/src/components/features/shows/ReviewForm/ReviewForm.tsx
> +            rating: parseInt(rating),
```suggestion
            rating,
```

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/src/components/features/shows/ReviewForm/ReviewForm.tsx
> +    }
Ovo bih radio inline ispod u formi

```suggestion
```

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/src/components/features/shows/ReviewForm/ReviewForm.tsx
> +                    <Textarea id="comment-input" backgroundColor={"white"} placeholder='Add comment' required></Textarea>
```suggestion
                    <Textarea
                        value={comment}
                        onChange={(event)=>{setComment(event.target.value)}}
                        backgroundColor={"white"}
                        placeholder='Add comment'
                        onChange={(event)=>{setComment(event.target.value)}}
                        required
                    />
```

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/src/components/features/shows/ReviewForm/ReviewForm.tsx
> +                    <StarRating label="Rating:" onChange={starRatingChange} value={starRatingValue} ></StarRating>
```suggestion
                    <StarRating
                        value={rating}
                        onChange={(value) => setRating(value)}
                        label="Rating:"
                    />
```

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/src/components/features/shows/ShowReviewSection/ShowReviewSection.tsx
> +
```suggestion
```

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/src/components/features/shows/ShowReviewSection/ShowReviewSection.tsx
> +        setReviews(loadReviewsFromLocalStorage);
```suggestion
        const loadedReviews = loadReviewsFromLocalStorage();
        setReviews(loadedReviews);
        updateRating(loadedReviews.reduce((sum, r)=> r.rating + sum, 0)/loadedReviews.length);
```

Zašto nisam napravio ovako nešto?
```
        setReviews(loadReviewsFromLocalStorage());
        updateRating(reviews.reduce((sum, r)=> r.rating + sum, 0)/reviews.length);
```

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/src/components/features/shows/ShowReviewSection/ShowReviewSection.tsx
> +    }, [reviews])
useEffect hookove ne bi bilo loše svesti na minimum. Ovaj nam recimo nije potreban.
Rating updateamo na inicijalni load (to može ovaj gore useEffect ishendlat), na dodavanje i brisanje.
Pa onda ovaj možemo maknuti
```suggestion
```

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/src/components/features/review/ReviewItem/ReviewItem.tsx
> +            <Button w={["100%", "100%", "fit-content"]} backgroundColor={"white"} color={"indigo"} rounded={20} onClick={onClickHandler}>Remove</Button>
Kad elementi ili komponente imaju više propertyja, radi preglednosti ih ovako složimo.
Osim toga, event handlere možemo dodavati inline ako izvršavaju samo jednu naredbu.

```suggestion
            <Button
                w={["100%", "100%", "fit-content"]}
                backgroundColor={"white"}
                color={"indigo"}
                rounded={20}
                onClick={() => removeReview(review)}
            >Remove</Button>
```

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/src/components/features/review/ReviewItem/ReviewItem.tsx
> +    }
Vezano za komentar ispod, ovo možemo maknut
```suggestion
```

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/src/components/features/review/ReviewList/ReviewList.tsx
> +            {reviews.map((review, index) => <ReviewItem key={index} review={review} removeReview={removeReview}></ReviewItem>)}
Da malo bude preglednije i komponentu napraviti kao self-closing
```suggestion
            {reviews.map((review, index) =>
                <ReviewItem
                    key={index}
                    review={review}
                    removeReview={removeReview}
                />
            )}
```

2024-07-07 16:46 UTC, ante-pesorda commented on tv-shows-app/src/components/features/shows/StarRating/StarRating.tsx
> +                    <StarIcon color={(value>=5)?"yellow":"white"} onClick={()=>{changeValue(5)}} onMouseEnter={()=>{onHoverHandler(5,true)}} onMouseLeave={()=>{onHoverHandler(5,false)}}></StarIcon>
Kako ti se čini ovo rješenje? U programiranju se ne volimo bespotrebno ponavljati, jer svaka naknadna izmjena onda traži puno posla. Recimo, iz nekog razloga želiš dodat treći argument metodi `onHoverHandler`. To bi onda bilo 15 izmjena, a ovako bi imali samo jednu
```suggestion
                    {
                        [...Array(5)].map((_, index) => {
                            return (
                                <StarIcon
                                    key={index}
                                    color={(value>=index+1)?"yellow":"white"}
                                    onClick={()=>{changeValue(index+1)}}
                                    onMouseEnter={()=>{onHoverHandler(index+1,true)}}
                                    onMouseLeave={()=>{onHoverHandler(index+1,false)}}
                                />
                            )
                        })
                    }
```

2024-07-07 17:26 UTC, Trexlo commented on tv-shows-app/src/components/features/shows/StarRating/StarRating.tsx
> +                    <StarIcon color={(value>=5)?"yellow":"white"} onClick={()=>{changeValue(5)}} onMouseEnter={()=>{onHoverHandler(5,true)}} onMouseLeave={()=>{onHoverHandler(5,false)}}></StarIcon>
to sam bas promijenio danas, i umjesto samih ikona sam ko i za proslu zadacu stavio radio buttone

2024-07-07 17:42 UTC, Trexlo commented on tv-shows-app/src/components/features/shows/ReviewForm/ReviewForm.tsx
> +    const [starRatingValue, setStarRatingValue] = useState(0);
ovdje starRatingValue mi više služi kao pomoć za display obojanih zvijezda pa bi to ostavio, rating je odabrana vrijednost na koju bi se starRatingValue vratio kada se dogodi OnMouseLeave, ali možda se to iz prošle verzije nije vidjelo

2024-07-10 08:18 UTC, ante-pesorda approved these changes

2024-07-10 08:19 UTC, merged